-- added table and table cell tables
CREATE TABLE
	`table` (
		`id` VARCHAR(255),
		`title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
		`userId` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci,
		`created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
		`updated_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
		PRIMARY KEY (id),
		CONSTRAINT `FK_1ascklqwd88cn3uijkld` FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE
	);

CREATE TABLE
	`table_cell` (
		id VARCHAR(255),
		`row` INT NOT NULL,
		`col` INT NOT NULL,
		`type` VARCHAR(255) CHARACTER SET
		utf8mb4 COLLATE utf8mb4_bin NOT NULL,
		`value` VARCHAR(255) CHARACTER SET
		utf8mb4 COLLATE utf8mb4_bin NOT NULL,
		`background` VARCHAR(32) CHARACTER SET
		utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL,
		`metadata` JSON NULL DEFAULT NULL,
		tableId VARCHAR(255) CHARACTER SET
		utf8 COLLATE utf8_general_ci,
		created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
		updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
		PRIMARY KEY (id),
		CONSTRAINT FK_1asckl67823hjkn83uijkld FOREIGN KEY (tableId) REFERENCES `table` (id) ON DELETE CASCADE ON UPDATE CASCADE
	);