import type { RequestTest } from '@modules/Core/Test/RequestTest'
import { z } from 'zod'
import { StatusCodes } from 'http-status-codes'

// Response schemas
const EmptyResponseScheme = z.object({})
const ErrorResponseSchema = z.object({ error: z.string() })

// Global dynamic variables (normally set during registration/login)
let capturedTeacherUsername = 'teacher'
let capturedStudentUsername = 'student'
let capturedAdminUsername = 'admin'
let capturedTeacherUserId = '01JJQ7JTHVFMABEBK2ANWKF5R1'
let capturedStudentUserId = '01J8VXMQDGEE4GCYSDSF8RY7E5'
let capturedAdminUserId = '01J6G76JDMH0FP47FW1RDDK1CC'
let capturedOtherUserId = '01HMC2PA3251RT43WWRYZSHHQ7'
let capturedMentorId = '01JJQ7NC1XYJ4MKWXNHA1GQDN1'
let capturedSubjectId = '01J59XHDM8419M0Z45P81CRH62'

const tests: RequestTest[] = [
  // 1) GET /user/:username => getByUsername
  {
    name: 'Get user by username as authenticated => 200',
    route: `/user/${capturedTeacherUsername}`,
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get user by invalid username => 400',
    route: '/user/???',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get user by username as unauth => 401',
    route: `/user/${capturedTeacherUsername}`,
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 2) PATCH /user/:username/verify-manual => verifyManual
  {
    name: 'Manually verify user as admin => 204',
    route: `/user/${capturedTeacherUsername}/verify-manual`,
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Manually verify user as teacher => 204',
    route: `/user/${capturedTeacherUsername}/verify-manual`,
    method: 'PATCH',
    authAs: 'teacher',
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Manually verify user as student => 403',
    route: `/user/${capturedTeacherUsername}/verify-manual`,
    method: 'PATCH',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Manually verify user as unauth => 401',
    route: `/user/${capturedTeacherUsername}/verify-manual`,
    method: 'PATCH',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Manually verify user with invalid username => 400',
    route: '/user/123???3123???!23/verify-manual',
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 3) GET /user/mentor/search => getMentors
  {
    name: 'Get mentors as teacher => 200',
    route: '/user/mentor/search',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get mentors as admin => 200',
    route: '/user/mentor/search',
    method: 'GET',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get mentors as student => 403',
    route: '/user/mentor/search',
    method: 'GET',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get mentors unauth => 401',
    route: '/user/mentor/search',
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 4) GET /user/teacher/search => getTeachers
  {
    name: 'Get teachers as admin => 200',
    route: '/user/teacher/search',
    method: 'GET',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get teachers as teacher => 200',
    route: '/user/teacher/search',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get teachers as student => 403',
    route: '/user/teacher/search',
    method: 'GET',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get teachers unauth => 401',
    route: '/user/teacher/search',
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 5) GET /user/student/search => getStudents
  {
    name: 'Get students as teacher => 200',
    route: '/user/student/search',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get students as student => 403',
    route: '/user/student/search',
    method: 'GET',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get students unauth => 401',
    route: '/user/student/search',
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 6) GET /user/student/search/own/:mentorId? => getMyStudents
  {
    name: 'Get my students with explicit mentorId as teacher => 200',
    route: `/user/student/search/own/${capturedMentorId}`,
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get my students with no mentorId as teacher => 200',
    route: '/user/student/search/own',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get my students as student => 403',
    route: `/user/student/search/own/${capturedMentorId}`,
    method: 'GET',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get my students unauth => 401',
    route: `/user/student/search/own/${capturedMentorId}`,
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Get my students with invalid mentorId => 400',
    route: '/user/student/search/own/bad-id',
    method: 'GET',
    authAs: 'teacher',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 7) GET /user/ => getUsers
  {
    name: 'Get users as admin => 200',
    route: '/user/',
    method: 'GET',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Get users as student => 403',
    route: '/user/',
    method: 'GET',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Get users unauth => 401',
    route: '/user/',
    method: 'GET',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 8) PATCH /user/:id => update
  {
    name: 'Update user as admin => 200',
    route: `/user/${capturedOtherUserId}`,
    method: 'PATCH',
    authAs: 'admin',
    body: { id: capturedOtherUserId, name: 'Updated Name' },
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update user as teacher => 200',
    route: `/user/${capturedOtherUserId}`,
    method: 'PATCH',
    authAs: 'teacher',
    body: { id: capturedOtherUserId, name: 'Updated Name' },
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update another user as student => 403',
    route: `/user/${capturedOtherUserId}`,
    method: 'PATCH',
    authAs: 'student',
    body: { id: capturedOtherUserId, name: 'ForbiddenUpdate' },
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update user with invalid ID => 400',
    route: '/user/not-a-valid-id',
    method: 'PATCH',
    authAs: 'admin',
    body: { firstName: 'InvalidID' },
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update user with invalid body => 400',
    route: `/user/${capturedOtherUserId}`,
    method: 'PATCH',
    authAs: 'admin',
    body: {},
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update user unauth => 401',
    route: `/user/${capturedOtherUserId}`,
    method: 'PATCH',
    body: { firstName: 'NoAuth' },
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 9) PATCH /user/:id/password => updatePassword
  {
    name: 'Update password as admin => 200',
    route: '/user/123/password',
    method: 'PATCH',
    authAs: 'admin',
    body: { oldPassword: 'old123', newPassword: 'new123' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update own password as student => 200',
    route: '/user/55/password',
    method: 'PATCH',
    authAs: 'student',
    body: { oldPassword: 'old', newPassword: 'new' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update another user’s password as student => 403',
    route: '/user/999/password',
    method: 'PATCH',
    authAs: 'student',
    body: { oldPassword: 'foo', newPassword: 'bar' },
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update password with invalid ID => 400',
    route: '/user/not-valid/password',
    method: 'PATCH',
    authAs: 'admin',
    body: { oldPassword: 'xxx', newPassword: 'yyy' },
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update password with invalid body => 400',
    route: '/user/123/password',
    method: 'PATCH',
    authAs: 'admin',
    body: {},
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update password unauth => 401',
    route: '/user/123/password',
    method: 'PATCH',
    body: { oldPassword: 'some', newPassword: 'thing' },
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 10) PATCH /user/:id/role => updateRole
  {
    name: 'Update user role as admin => 200',
    route: `/user/${capturedOtherUserId}/role`,
    method: 'PATCH',
    authAs: 'admin',
    body: { role: 'mentor' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update user role as teacher => 200',
    route: `/user/${capturedOtherUserId}/role`,
    method: 'PATCH',
    authAs: 'teacher',
    body: { role: 'student' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update user role as student => 403',
    route: `/user/${capturedOtherUserId}/role`,
    method: 'PATCH',
    authAs: 'student',
    body: { role: 'teacher' },
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update user role unauth => 401',
    route: `/user/${capturedOtherUserId}/role`,
    method: 'PATCH',
    body: { role: 'admin' },
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Update user role with invalid ID => 400',
    route: '/user/bad-id/role',
    method: 'PATCH',
    authAs: 'admin',
    body: { role: 'teacher' },
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update user role with invalid body => 400',
    route: '/user/444/role',
    method: 'PATCH',
    authAs: 'admin',
    body: {},
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 11) PATCH /user/:id/telegram => updateTelegram
  {
    name: 'Update telegram as admin => 200',
    route: '/user/777/telegram',
    method: 'PATCH',
    authAs: 'admin',
    body: { telegramUsername: '@mytelegram' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update telegram as teacher => 200',
    route: '/user/777/telegram',
    method: 'PATCH',
    authAs: 'teacher',
    body: { telegramUsername: '@teachertelegram' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update own telegram as student => 200',
    route: '/user/55/telegram',
    method: 'PATCH',
    authAs: 'student',
    body: { telegramUsername: '@studenttelegram' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update another user’s telegram as student => 403',
    route: '/user/999/telegram',
    method: 'PATCH',
    authAs: 'student',
    body: { telegramUsername: '@forbidden' },
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update telegram with invalid ID => 400',
    route: '/user/not-valid/telegram',
    method: 'PATCH',
    authAs: 'admin',
    body: { telegramUsername: 'xxx' },
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update telegram with invalid body => 400',
    route: '/user/777/telegram',
    method: 'PATCH',
    authAs: 'admin',
    body: {},
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update telegram unauth => 401',
    route: '/user/777/telegram',
    method: 'PATCH',
    body: { telegramUsername: 'xxx' },
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 12) PATCH /user/:id/email => updateEmail
  {
    name: 'Update email as admin => 200',
    route: '/user/888/email',
    method: 'PATCH',
    authAs: 'admin',
    body: { email: 'new@example.com' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update own email as student => 200',
    route: '/user/55/email',
    method: 'PATCH',
    authAs: 'student',
    body: { email: 'student@mail.com' },
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Update another user’s email as student => 403',
    route: '/user/999/email',
    method: 'PATCH',
    authAs: 'student',
    body: { email: 'forbidden@mail.com' },
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update email with invalid ID => 400',
    route: '/user/not-valid/email',
    method: 'PATCH',
    authAs: 'admin',
    body: { email: 'test@mail.com' },
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update email with invalid body => 400',
    route: '/user/888/email',
    method: 'PATCH',
    authAs: 'admin',
    body: {},
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Update email unauth => 401',
    route: '/user/888/email',
    method: 'PATCH',
    body: { email: 'test@mail.com' },
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },

  // 13) PATCH /user/:id/block => block
  {
    name: 'Block user as admin => 200',
    route: '/user/999/block',
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Block user as teacher => 200',
    route: '/user/999/block',
    method: 'PATCH',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Block user as student => 403',
    route: '/user/999/block',
    method: 'PATCH',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Block user unauth => 401',
    route: '/user/999/block',
    method: 'PATCH',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Block user with invalid ID => 400',
    route: '/user/invalid/block',
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 14) PATCH /user/:id/unblock => unblock
  {
    name: 'Unblock user as admin => 200',
    route: '/user/999/unblock',
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Unblock user as teacher => 200',
    route: '/user/999/unblock',
    method: 'PATCH',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Unblock user as student => 403',
    route: '/user/999/unblock',
    method: 'PATCH',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Unblock user unauth => 401',
    route: '/user/999/unblock',
    method: 'PATCH',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Unblock user with invalid ID => 400',
    route: '/user/invalid/unblock',
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 15) PATCH /user/:studentId/:subjectId/mentor/:mentorId => assignMentor
  {
    name: 'Assign mentor as teacher => 200',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor/${capturedMentorId}`,
    method: 'PATCH',
    authAs: 'teacher',
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Assign mentor as admin => 200',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor/${capturedMentorId}`,
    method: 'PATCH',
    authAs: 'admin',
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Assign mentor as student => 403',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor/${capturedMentorId}`,
    method: 'PATCH',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Assign mentor unauth => 401',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor/${capturedMentorId}`,
    method: 'PATCH',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Assign mentor with invalid IDs => 400',
    route: '/user/notID/222/mentor/333',
    method: 'PATCH',
    authAs: 'teacher',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 16) DELETE /user/:studentId/:subjectId/mentor => unassignMentor
  {
    name: 'Unassign mentor as admin => 200',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor`,
    method: 'DELETE',
    authAs: 'admin',
    expectedStatus: StatusCodes.NO_CONTENT,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Unassign mentor as teacher => 200',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor`,
    method: 'DELETE',
    authAs: 'teacher',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Unassign mentor as student => 403',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor`,
    method: 'DELETE',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Unassign mentor unauth => 401',
    route: `/user/${capturedStudentUserId}/${capturedSubjectId}/mentor`,
    method: 'DELETE',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
  {
    name: 'Unassign mentor with invalid IDs => 400',
    route: '/user/xxx/222/mentor',
    method: 'DELETE',
    authAs: 'teacher',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },

  // 17) DELETE /user/:id/:password => delete
  {
    name: 'Delete user as admin => 200',
    route: `/user/${capturedOtherUserId}/secret123`,
    method: 'DELETE',
    authAs: 'admin',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Delete own account as student => 200',
    route: `/user/${capturedStudentUserId}/studentPass`,
    method: 'DELETE',
    authAs: 'student',
    expectedStatus: StatusCodes.OK,
    responseSchema: EmptyResponseScheme,
  },
  {
    name: 'Delete another user as student => 403',
    route: `/user/${capturedOtherUserId}/wrongPass`,
    method: 'DELETE',
    authAs: 'student',
    expectedStatus: StatusCodes.FORBIDDEN,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Delete user with invalid ID => 400',
    route: '/user/not-valid/pass123',
    method: 'DELETE',
    authAs: 'admin',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Delete user with invalid password param => 400',
    route: '/user/999/',
    method: 'DELETE',
    authAs: 'admin',
    expectedStatus: StatusCodes.BAD_REQUEST,
    responseSchema: ErrorResponseSchema,
  },
  {
    name: 'Delete user unauth => 401',
    route: '/user/999/pass',
    method: 'DELETE',
    expectedStatus: StatusCodes.UNAUTHORIZED,
    responseSchema: ErrorResponseSchema.optional(),
  },
]

export default tests
